- name: celery-docker
# ssh github_blog
  hosts: celery-docker
  become: yes
  vars:
    container_name: "celery-docker"
    container_image: "andrewpasis/celery-docker"
    env_file: "/home/ubuntu/celery-docker/.env"

  tasks:
  - name: install pip3
    apt:
      name: python3-pip
      update_cache: yes
      state: present
  - name: pip install docker-py
    pip: name=docker-py

  - name: Start a container and use an env file
    docker_container:
      name: "{{ container_name }}"
      image: "{{ container_image }}"
      pull: true
      state: started
      restart: yes
      ports:
       - "8002:8002"
      env_file: "{{ env_file }}"

# docker exec -it "$(sudo docker ps -qf name=github_blog)" sh
# python manage.py migrate
# python manage.py runserver 0.0.0.0:8001
# python manage.py collect_github
# python manage.py staticgen http://127.0.0.1:8000 /html

# docker run -p 8000:8000 --env-file .env <container_name>
# docker stop <container_id>
# docker system prune
# docker logs github_blog
